--deðerler 
CREATE TABLE #TEMP (
	[HESAPKODU] [nvarchar] (50)  NULL ,
	[HESAPADI] [nvarchar] (100) NULL ,
	[CBORC] [decimal](28, 8) NULL ,
	[CALACAK] [decimal](28, 8) NULL ,
	[BAKIYE] [decimal](28, 8) NULL ,
	[DOVIZBORC] [decimal](28, 8) NULL ,
	[DOVIZALACAK] [decimal](28, 8) NULL ,
	[DBAKIYE] [decimal](28, 8) NULL ,
	[GIRENMIKTAR] [decimal](28, 8) NULL ,
	[CIKANMIKTAR] [decimal](28, 8) NULL ,
	[KALANMIKTAR] [decimal](28, 8) NULL )

declare @EFORMAT smallint,@SEVIYE smallint,@SEVIYEADI nvarchar(20),@FORMAT int

DECLARE cur CURSOR FOR 
SELECT SEVIYE,SEVIYEADI,[FORMAT]
FROM *!F!DTBLSEVTAN
OPEN cur
FETCH NEXT FROM cur 
INTO @SEVIYE ,@SEVIYEADI ,@FORMAT 
set @EFORMAT=7 --@FORMAT
WHILE @@FETCH_STATUS = 0 
BEGIN
print 'Begin'
if not @SEVIYE<>2
begin
print '1. seviye'
INSERT INTO #TEMP
SELECT 
SUBSTRING(ISLEM.HESAPKODU,1,@FORMAT) AS HESAPKODU
,HESAP.HESAPADI,
isnull(SUM(ISLEM.BORC) / 1,0) AS CBORC,
isnull(SUM(ISLEM.ALACAK) / 1,0) AS CALACAK,
((SUM(ISLEM.BORC) / 1)-(SUM(ISLEM.ALACAK) / 1)) as BAKIYE,
isnull (SUM(ISLEM.DBORC),0) AS DOVIZBORC,isnull(SUM(ISLEM.DALACAK),0) AS DOVIZALACAK,
isnull((SUM(ISLEM.DBORC))-(SUM(ISLEM.DALACAK)),0) as DBAKIYE,isnull(SUM(ISLEM.BMIKTAR),0) AS GIRENMIKTAR,
isnull(SUM(ISLEM.AMIKTAR),0) AS CIKANMIKTAR,isnull((SUM(ISLEM.BMIKTAR))-(SUM(ISLEM.AMIKTAR)),0) as KALANMIKTAR 
FROM *!F!DTBLISLEM AS ISLEM LEFT JOIN *!F!DTBLHESAP AS HESAP 
ON HESAP.HESAPKODU=SUBSTRING(ISLEM.HESAPKODU,1,@FORMAT) 
WHERE ISLEM.FISTIPI='N' 
 GROUP BY SUBSTRING(ISLEM.HESAPKODU,1,@FORMAT) 
,HESAP.HESAPADI 
ORDER BY SUBSTRING(ISLEM.HESAPKODU,1,@FORMAT)
end
else
begin
INSERT INTO #TEMP
SELECT 
REPLACE(REPLACE(ISLEM.HESAPKODU,'XXXX','.'),'XXX','.') AS HESAPKODU

--SUBSTRING(ISLEM.HESAPKODU,1,@FORMAT+@EFORMAT ) AS HESAPKODU
,HESAP.HESAPADI,
isnull(SUM(ISLEM.BORC) / 1,0) AS CBORC,
isnull(SUM(ISLEM.ALACAK) / 1,0) AS CALACAK,
((SUM(ISLEM.BORC) / 1)-(SUM(ISLEM.ALACAK) / 1)) as BAKIYE,
isnull (SUM(ISLEM.DBORC),0) AS DOVIZBORC,isnull(SUM(ISLEM.DALACAK),0) AS DOVIZALACAK,
isnull((SUM(ISLEM.DBORC))-(SUM(ISLEM.DALACAK)),0) as DBAKIYE,isnull(SUM(ISLEM.BMIKTAR),0) AS GIRENMIKTAR,
isnull(SUM(ISLEM.AMIKTAR),0) AS CIKANMIKTAR,isnull((SUM(ISLEM.BMIKTAR))-(SUM(ISLEM.AMIKTAR)),0) as KALANMIKTAR 
FROM *!F!DTBLISLEM AS ISLEM LEFT JOIN *!F!DTBLHESAP AS HESAP 
ON REPLACE(REPLACE(HESAP.HESAPKODU,'XXXX','.'),'XXX','.')=REPLACE(REPLACE(ISLEM.HESAPKODU,'XXXX','.'),'XXX','.')
WHERE ISLEM.FISTIPI='N' 
 GROUP BY REPLACE(REPLACE(ISLEM.HESAPKODU,'XXXX','.'),'XXX','.')
,HESAP.HESAPADI 
ORDER BY REPLACE(REPLACE(ISLEM.HESAPKODU,'XXXX','.'),'XXX','.')
set @EFORMAT=@EFORMAT+@FORMAT+2
end
FETCH NEXT FROM cur 
INTO @SEVIYE ,@SEVIYEADI ,@FORMAT 

END
CLOSE cur
DEALLOCATE cur

select distinct * from #TEMP
drop table #TEMP
go